kind = "DojoContract"
class_hash = "0x11472c33465ac19ee8fd27f6d901c6c4c68ec3b7aca25da683f9ada76edf5ff"
original_class_hash = "0x11472c33465ac19ee8fd27f6d901c6c4c68ec3b7aca25da683f9ada76edf5ff"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-guild_actions-4c9f5931.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-guild_actions"
systems = [
    "add_member",
    "remove_member",
]
manifest_name = "pixelaw-guild_actions-4c9f5931"
