kind = "DojoContract"
class_hash = "0x5fcab7a1d0e411ba71e2ee801838b03821ecb847a2a8c2297769569758edf87"
original_class_hash = "0x5fcab7a1d0e411ba71e2ee801838b03821ecb847a2a8c2297769569758edf87"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-guild_actions-4c9f5931.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-guild_actions"
systems = [
    "add_member",
    "remove_member",
]
manifest_name = "pixelaw-guild_actions-4c9f5931"
