[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x263ae44e5414519a5c5a135cccaf3d9d7ee196d37e8de47a178da91f3de9b34"
transaction_hash = "0x507cd13b0e34b357d25bd0ddafa527c8caf0729f894e57ad9129c1f29311768"
block_number = 3
seed = "pixelaw"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x6c2ffdd97cb5a1bca13de416adb23a1d0e24ae3c805114b2100f6af95a7f60e"
class_hash = "0x17d390af6c3b449b52da5a0969a00006a3b7935ffc08192dc8cefdeb563488f"
original_class_hash = "0x17d390af6c3b449b52da5a0969a00006a3b7935ffc08192dc8cefdeb563488f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pixelaw-actions-16928a49.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-actions"
systems = [
    "init",
    "update_permission",
    "schedule_queue",
    "process_queue",
    "update_pixel",
    "alert_player",
    "set_instruction",
]
manifest_name = "pixelaw-actions-16928a49"

[[contracts]]
kind = "DojoContract"
address = "0x2045bbeab298c52664537ae151262ca5f2a4e41b07f221c4860879551c65cb5"
class_hash = "0x21cec3b0828e4b206170a9eba80f3cdea068c53ab9ba00196b996dc6aa266c4"
original_class_hash = "0x21cec3b0828e4b206170a9eba80f3cdea068c53ab9ba00196b996dc6aa266c4"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pixelaw-p_war_actions-60819afd.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_war_actions"
systems = [
    "on_pre_update",
    "on_post_update",
    "set_pixel",
    "init",
    "interact",
    "place_pixel",
    "update_pixel",
    "end_game",
]
manifest_name = "pixelaw-p_war_actions-60819afd"

[[contracts]]
kind = "DojoContract"
address = "0x72e4bb5459874f51d4d2204d4d0b00719087cd5dcd1957bbac5473152d348ea"
class_hash = "0x84bd3040033c83ad370fed726f4697fc76e7f16e1d254e66de26e767a78653"
original_class_hash = "0x84bd3040033c83ad370fed726f4697fc76e7f16e1d254e66de26e767a78653"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pixelaw-propose-70d0002d.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-propose"
systems = ["activate_proposal"]
manifest_name = "pixelaw-propose-70d0002d"

[[contracts]]
kind = "DojoContract"
address = "0x1a7d8c29568c3ca9c2f4308ed04a790fbb8a6b07e8801f02c589946566896d6"
class_hash = "0x9e27330384b6dab78836d58d402a04da9c4a746244179ae59969917e6eec74"
original_class_hash = "0x9e27330384b6dab78836d58d402a04da9c4a746244179ae59969917e6eec74"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pixelaw-voting-324fa594.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-voting"
systems = ["vote"]
manifest_name = "pixelaw-voting-324fa594"

[[models]]
kind = "DojoModel"
class_hash = "0x2e21c14e524e53add7e001d5ff402bbb8573d8bfabfee7025eaa755aa6e729f"
original_class_hash = "0x2e21c14e524e53add7e001d5ff402bbb8573d8bfabfee7025eaa755aa6e729f"
abi = "manifests/dev/deployment/abis/models/pixelaw-AllowedApp-4aa27058.json"
tag = "pixelaw-AllowedApp"
qualified_path = "p_war::models::allowed_app::allowed_app"
manifest_name = "pixelaw-AllowedApp-4aa27058"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "contract"
type = "ContractAddress"
key = true

[[models.members]]
name = "is_allowed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x661de232e8fd024ceef7e099030347690f4e8280bc50840982c6cab3298da54"
original_class_hash = "0x661de232e8fd024ceef7e099030347690f4e8280bc50840982c6cab3298da54"
abi = "manifests/dev/deployment/abis/models/pixelaw-AllowedColor-22c1a796.json"
tag = "pixelaw-AllowedColor"
qualified_path = "p_war::models::allowed_color::allowed_color"
manifest_name = "pixelaw-AllowedColor-22c1a796"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "color"
type = "u32"
key = true

[[models.members]]
name = "is_allowed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4107d94a66470b68d2e06102c87937c03cca51fafa84a3a4fc45c95a4d2403c"
original_class_hash = "0x4107d94a66470b68d2e06102c87937c03cca51fafa84a3a4fc45c95a4d2403c"
abi = "manifests/dev/deployment/abis/models/pixelaw-App-36504565.json"
tag = "pixelaw-App"
qualified_path = "pixelaw::core::models::registry::app"
manifest_name = "pixelaw-App-36504565"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "icon"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
original_class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
abi = "manifests/dev/deployment/abis/models/pixelaw-AppName-3b816829.json"
tag = "pixelaw-AppName"
qualified_path = "pixelaw::core::models::registry::app_name"
manifest_name = "pixelaw-AppName-3b816829"

[[models.members]]
name = "name"
type = "felt252"
key = true

[[models.members]]
name = "system"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d55e23acf8df5ef0c25b76d5a6b7765c241c494af075c7ce3858568bec45f1"
original_class_hash = "0x3d55e23acf8df5ef0c25b76d5a6b7765c241c494af075c7ce3858568bec45f1"
abi = "manifests/dev/deployment/abis/models/pixelaw-AppUser-4eda3c52.json"
tag = "pixelaw-AppUser"
qualified_path = "pixelaw::core::models::registry::app_user"
manifest_name = "pixelaw-AppUser-4eda3c52"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x38dd4eb04738175abe3d1d4b2541dbf6c318004fe9a76d5181001bfe72ae66c"
original_class_hash = "0x38dd4eb04738175abe3d1d4b2541dbf6c318004fe9a76d5181001bfe72ae66c"
abi = "manifests/dev/deployment/abis/models/pixelaw-Board-124dc3e7.json"
tag = "pixelaw-Board"
qualified_path = "p_war::models::board::board"
manifest_name = "pixelaw-Board-124dc3e7"

[[models.members]]
name = "id"
type = "usize"
key = true

[[models.members]]
name = "origin"
type = "Position"
key = false

[[models.members]]
name = "width"
type = "u32"
key = false

[[models.members]]
name = "height"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
original_class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
abi = "manifests/dev/deployment/abis/models/pixelaw-CoreActionsAddress-5379e1ce.json"
tag = "pixelaw-CoreActionsAddress"
qualified_path = "pixelaw::core::models::registry::core_actions_address"
manifest_name = "pixelaw-CoreActionsAddress-5379e1ce"

[[models.members]]
name = "key"
type = "felt252"
key = true

[[models.members]]
name = "value"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xae291a350d93211b1adcc4ece17b19ec53ff50207b01be6fc0c39cfc7974b9"
original_class_hash = "0xae291a350d93211b1adcc4ece17b19ec53ff50207b01be6fc0c39cfc7974b9"
abi = "manifests/dev/deployment/abis/models/pixelaw-Game-5c1fa23f.json"
tag = "pixelaw-Game"
qualified_path = "p_war::models::game::game"
manifest_name = "pixelaw-Game-5c1fa23f"

[[models.members]]
name = "id"
type = "usize"
key = true

[[models.members]]
name = "start"
type = "u64"
key = false

[[models.members]]
name = "end"
type = "u64"
key = false

[[models.members]]
name = "proposal_idx"
type = "usize"
key = false

[[models.members]]
name = "base_cost"
type = "u32"
key = false

[[models.members]]
name = "const_val"
type = "u32"
key = false

[[models.members]]
name = "coeff_own_pixels"
type = "u32"
key = false

[[models.members]]
name = "coeff_commits"
type = "u32"
key = false

[[models.members]]
name = "winner_config"
type = "u32"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x22a02c0555eedefbbf217bf90fa1796bd4e113b4ee5f79007ea3d271181c2f4"
original_class_hash = "0x22a02c0555eedefbbf217bf90fa1796bd4e113b4ee5f79007ea3d271181c2f4"
abi = "manifests/dev/deployment/abis/models/pixelaw-GameId-1ee8756e.json"
tag = "pixelaw-GameId"
qualified_path = "p_war::models::board::game_id"
manifest_name = "pixelaw-GameId-1ee8756e"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "usize"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71970d089bfc265a629cb22eb01266723e8db49ae13a35bc1a53867a38d7398"
original_class_hash = "0x71970d089bfc265a629cb22eb01266723e8db49ae13a35bc1a53867a38d7398"
abi = "manifests/dev/deployment/abis/models/pixelaw-GamePalette-49013f2b.json"
tag = "pixelaw-GamePalette"
qualified_path = "p_war::models::allowed_color::game_palette"
manifest_name = "pixelaw-GamePalette-49013f2b"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "length"
type = "usize"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x42e6b8f760d9ae43dfdac6767b2c7e12ea881dfbe10ccac7c30d2ed025ac372"
original_class_hash = "0x42e6b8f760d9ae43dfdac6767b2c7e12ea881dfbe10ccac7c30d2ed025ac372"
abi = "manifests/dev/deployment/abis/models/pixelaw-InPalette-7a46e3ad.json"
tag = "pixelaw-InPalette"
qualified_path = "p_war::models::allowed_color::in_palette"
manifest_name = "pixelaw-InPalette-7a46e3ad"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "color"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x710dc73b9f03542890421c368ca53fe61416010f69709337bc7b40b9c3115af"
original_class_hash = "0x710dc73b9f03542890421c368ca53fe61416010f69709337bc7b40b9c3115af"
abi = "manifests/dev/deployment/abis/models/pixelaw-Instruction-4c7c4844.json"
tag = "pixelaw-Instruction"
qualified_path = "pixelaw::core::models::registry::instruction"
manifest_name = "pixelaw-Instruction-4c7c4844"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "selector"
type = "felt252"
key = true

[[models.members]]
name = "instruction"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3f15ee957414f1442830161943dfac7ca65fb77b5a9a2ed2e53099d8493c261"
original_class_hash = "0x3f15ee957414f1442830161943dfac7ca65fb77b5a9a2ed2e53099d8493c261"
abi = "manifests/dev/deployment/abis/models/pixelaw-PWarPixel-15195913.json"
tag = "pixelaw-PWarPixel"
qualified_path = "p_war::models::board::p_war_pixel"
manifest_name = "pixelaw-PWarPixel-15195913"

[[models.members]]
name = "position"
type = "Position"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x37fca9c9d7ab57dda36b03416d16bfc625e9b0e6187c8f7f73030225c9b5444"
original_class_hash = "0x37fca9c9d7ab57dda36b03416d16bfc625e9b0e6187c8f7f73030225c9b5444"
abi = "manifests/dev/deployment/abis/models/pixelaw-PaletteColors-39a92a0a.json"
tag = "pixelaw-PaletteColors"
qualified_path = "p_war::models::allowed_color::palette_colors"
manifest_name = "pixelaw-PaletteColors-39a92a0a"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "idx"
type = "u32"
key = true

[[models.members]]
name = "color"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
original_class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
abi = "manifests/dev/deployment/abis/models/pixelaw-Permissions-72b77307.json"
tag = "pixelaw-Permissions"
qualified_path = "pixelaw::core::models::permissions::permissions"
manifest_name = "pixelaw-Permissions-72b77307"

[[models.members]]
name = "allowing_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "allowed_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "permission"
type = "Permission"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
original_class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
abi = "manifests/dev/deployment/abis/models/pixelaw-Pixel-7e607b2f.json"
tag = "pixelaw-Pixel"
qualified_path = "pixelaw::core::models::pixel::pixel"
manifest_name = "pixelaw-Pixel-7e607b2f"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "app"
type = "ContractAddress"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "created_at"
type = "u64"
key = false

[[models.members]]
name = "updated_at"
type = "u64"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x432d5d7bf204934886fa3dc72b24ad292b14caf4bea83531cef5004d7cb5067"
original_class_hash = "0x432d5d7bf204934886fa3dc72b24ad292b14caf4bea83531cef5004d7cb5067"
abi = "manifests/dev/deployment/abis/models/pixelaw-PixelRecoveryRate-3aa284c0.json"
tag = "pixelaw-PixelRecoveryRate"
qualified_path = "p_war::models::proposal::pixel_recovery_rate"
manifest_name = "pixelaw-PixelRecoveryRate-3aa284c0"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "rate"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x73f4c14a1b7cfadff6bdad338ebacc61fa1c429a6610fd00480312ec6f37180"
original_class_hash = "0x73f4c14a1b7cfadff6bdad338ebacc61fa1c429a6610fd00480312ec6f37180"
abi = "manifests/dev/deployment/abis/models/pixelaw-Player-30a1b371.json"
tag = "pixelaw-Player"
qualified_path = "p_war::models::player::player"
manifest_name = "pixelaw-Player-30a1b371"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_px"
type = "u32"
key = false

[[models.members]]
name = "num_owns"
type = "u32"
key = false

[[models.members]]
name = "num_commit"
type = "u32"
key = false

[[models.members]]
name = "current_px"
type = "u32"
key = false

[[models.members]]
name = "last_date"
type = "u64"
key = false

[[models.members]]
name = "is_banned"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x249aaae81a4275050c7d9f959c5b09c1babbd39b47697bb895adc72cf7965c5"
original_class_hash = "0x249aaae81a4275050c7d9f959c5b09c1babbd39b47697bb895adc72cf7965c5"
abi = "manifests/dev/deployment/abis/models/pixelaw-PlayerVote-326c17c6.json"
tag = "pixelaw-PlayerVote"
qualified_path = "p_war::models::proposal::player_vote"
manifest_name = "pixelaw-PlayerVote-326c17c6"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "index"
type = "usize"
key = true

[[models.members]]
name = "is_in_favor"
type = "bool"
key = false

[[models.members]]
name = "px"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x404d31fa774f450e44ff386730f3f43c2932d7cfcc55251e2a0ef2c77f5dc96"
original_class_hash = "0x404d31fa774f450e44ff386730f3f43c2932d7cfcc55251e2a0ef2c77f5dc96"
abi = "manifests/dev/deployment/abis/models/pixelaw-Proposal-49e1daf5.json"
tag = "pixelaw-Proposal"
qualified_path = "p_war::models::proposal::proposal"
manifest_name = "pixelaw-Proposal-49e1daf5"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "index"
type = "usize"
key = true

[[models.members]]
name = "author"
type = "ContractAddress"
key = false

[[models.members]]
name = "proposal_type"
type = "u8"
key = false

[[models.members]]
name = "target_args_1"
type = "u32"
key = false

[[models.members]]
name = "target_args_2"
type = "u32"
key = false

[[models.members]]
name = "start"
type = "u64"
key = false

[[models.members]]
name = "end"
type = "u64"
key = false

[[models.members]]
name = "yes_px"
type = "u32"
key = false

[[models.members]]
name = "no_px"
type = "u32"
key = false

[[models.members]]
name = "is_activated"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
original_class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
abi = "manifests/dev/deployment/abis/models/pixelaw-QueueItem-549a17f2.json"
tag = "pixelaw-QueueItem"
qualified_path = "pixelaw::core::models::queue::queue_item"
manifest_name = "pixelaw-QueueItem-549a17f2"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "valid"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
original_class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
abi = "manifests/dev/deployment/abis/models/pixelaw-Snake-62b876d4.json"
tag = "pixelaw-Snake"
qualified_path = "pixelaw::apps::snake::app::snake"
manifest_name = "pixelaw-Snake-62b876d4"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "length"
type = "u8"
key = false

[[models.members]]
name = "first_segment_id"
type = "u32"
key = false

[[models.members]]
name = "last_segment_id"
type = "u32"
key = false

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "is_dying"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x19a1ae61a4fb0ac303e15a4ca4befa5ae3962625eb37f379b941815e321191f"
original_class_hash = "0x19a1ae61a4fb0ac303e15a4ca4befa5ae3962625eb37f379b941815e321191f"
abi = "manifests/dev/deployment/abis/models/pixelaw-SnakeSegment-302de0d8.json"
tag = "pixelaw-SnakeSegment"
qualified_path = "pixelaw::apps::snake::app::snake_segment"
manifest_name = "pixelaw-SnakeSegment-302de0d8"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "previous_id"
type = "u32"
key = false

[[models.members]]
name = "next_id"
type = "u32"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_color"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_text"
type = "felt252"
key = false

[[models.members]]
name = "pixel_original_app"
type = "ContractAddress"
key = false
