kind = "DojoContract"
class_hash = "0x63080ea2cfae99d4b773b06c7d1cb893c197ba5e431afeba8909eac874d038e"
original_class_hash = "0x63080ea2cfae99d4b773b06c7d1cb893c197ba5e431afeba8909eac874d038e"
base_class_hash = "0x0"
abi = "manifests/release/base/abis/contracts/pixelaw-guild_actions-4c9f5931.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-guild_actions"
systems = [
    "add_member",
    "remove_member",
]
manifest_name = "pixelaw-guild_actions-4c9f5931"
