kind = "DojoContract"
class_hash = "0x76a41721719a58f3dd43429eecfff5ed72ff993d653f417bdb337418ec8e589"
original_class_hash = "0x76a41721719a58f3dd43429eecfff5ed72ff993d653f417bdb337418ec8e589"
base_class_hash = "0x0"
abi = "manifests/release/base/abis/contracts/pixelaw-propose_actions-4ee7028a.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-propose_actions"
systems = ["activate_proposal"]
manifest_name = "pixelaw-propose_actions-4ee7028a"
