kind = "DojoContract"
class_hash = "0xdfa69aecb748b5e097a5dc04b9cc1ed8b666a5cc72c725ee5f0ca1acca12d"
original_class_hash = "0xdfa69aecb748b5e097a5dc04b9cc1ed8b666a5cc72c725ee5f0ca1acca12d"
base_class_hash = "0x0"
abi = "manifests/release/base/abis/contracts/pixelaw-propose_actions-4ee7028a.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-propose_actions"
systems = ["activate_proposal"]
manifest_name = "pixelaw-propose_actions-4ee7028a"
