tag = "pixelaw-actions"
writes = [
    "pixelaw-App",
    "pixelaw-AppName",
    "pixelaw-CoreActionsAddress",
    "pixelaw-Pixel",
    "pixelaw-Permissions",
    "pixelaw-QueueItem",
    "pixelaw-Instruction",
    "pixelaw-PWarPixel",
    "pixelaw-AllowedColor",
    "pixelaw-PaletteColors",
]
