tag = "pixelaw-p_war_actions"
writes = [
    "pixelaw-AllowedApp",
    "pixelaw-Board",
    "pixelaw-AllowedColor",
    "pixelaw-PaletteColors",
    "pixelaw-PWarPixel",
    "pixelaw-Game",
    "pixelaw-GameId",
    "pixelaw-GamePalette",
    "pixelaw-InPalette",
    "pixelaw-Player",
    "pixelaw-PixelRecoveryRate",
]
