tag = "pixelaw-propose_actions"
writes = [
    "pixelaw-AllowedColor",
    "pixelaw-GamePalette",
    "pixelaw-InPalette",
    "pixelaw-PaletteColors",
    "pixelaw-Proposal",
    "pixelaw-Player",
    "pixelaw-Game",
    "pixelaw-Board",
]
