kind = "DojoModel"
class_hash = "0x54ea4b52cb546ddc0cd309cd998980b20b333d9cec4dd148a8da1a2500cff95"
original_class_hash = "0x54ea4b52cb546ddc0cd309cd998980b20b333d9cec4dd148a8da1a2500cff95"
abi = "manifests/release/base/abis/models/pixelaw-Guild-40e97c00.json"
tag = "pixelaw-Guild"
qualified_path = "p_war::models::guilds::guild"
manifest_name = "pixelaw-Guild-40e97c00"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "guild_id"
type = "usize"
key = true

[[members]]
name = "guild_name"
type = "felt252"
key = false

[[members]]
name = "creator"
type = "ContractAddress"
key = false

[[members]]
name = "members"
type = "Span<ContractAddress>"
key = false

[[members]]
name = "member_count"
type = "usize"
key = false
