kind = "DojoModel"
class_hash = "0x249aaae81a4275050c7d9f959c5b09c1babbd39b47697bb895adc72cf7965c5"
original_class_hash = "0x249aaae81a4275050c7d9f959c5b09c1babbd39b47697bb895adc72cf7965c5"
abi = "manifests/release/base/abis/models/pixelaw-PlayerVote-326c17c6.json"
tag = "pixelaw-PlayerVote"
qualified_path = "p_war::models::proposal::player_vote"
manifest_name = "pixelaw-PlayerVote-326c17c6"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "index"
type = "usize"
key = true

[[members]]
name = "is_in_favor"
type = "bool"
key = false

[[members]]
name = "px"
type = "u32"
key = false
