kind = "DojoModel"
class_hash = "0x71a6f6188f355d1337561c8d68538b18ec4be4c493d01be5eee753759246848"
original_class_hash = "0x71a6f6188f355d1337561c8d68538b18ec4be4c493d01be5eee753759246848"
abi = "manifests/release/base/abis/models/pixelaw-Player-30a1b371.json"
tag = "pixelaw-Player"
qualified_path = "p_war::models::player::player"
manifest_name = "pixelaw-Player-30a1b371"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "num_owns"
type = "u32"
key = false

[[members]]
name = "num_commit"
type = "u32"
key = false

[[members]]
name = "last_date"
type = "u64"
key = false

[[members]]
name = "is_banned"
type = "bool"
key = false
