kind = "DojoModel"
class_hash = "0xb96c0eea2bd6db369ba41c859e41e3bd5829bece04908e48b0b8702b88619d"
original_class_hash = "0xb96c0eea2bd6db369ba41c859e41e3bd5829bece04908e48b0b8702b88619d"
abi = "manifests/dev/abis/base/models/p_war_models_proposal_proposal.json"
name = "p_war::models::proposal::proposal"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "index"
type = "usize"
key = true

[[members]]
name = "author"
type = "ContractAddress"
key = false

[[members]]
name = "terms"
type = "Terms"
key = false

[[members]]
name = "start"
type = "u64"
key = false

[[members]]
name = "end"
type = "u64"
key = false

[[members]]
name = "yes_px"
type = "u32"
key = false

[[members]]
name = "no_px"
type = "u32"
key = false
