kind = "DojoModel"
class_hash = "0x29d1418c318a83af2fd02b38c9114742d56eda05cdcbd13d57f70cd8433b749"
original_class_hash = "0x29d1418c318a83af2fd02b38c9114742d56eda05cdcbd13d57f70cd8433b749"
abi = "manifests/dev/abis/base/models/p_war_models_moves_moves.json"
name = "p_war::models::moves::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false
