kind = "DojoModel"
class_hash = "0x3a759caf62afb2fd084ecc63d77ec528c50774246b658c9ac485915707676af"
original_class_hash = "0x3a759caf62afb2fd084ecc63d77ec528c50774246b658c9ac485915707676af"
abi = "manifests/dev/abis/base/models/p_war_models_board_p_war_pixel.json"
name = "p_war::models::board::p_war_pixel"

[[members]]
name = "position"
type = "Position"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = false
