kind = "DojoModel"
class_hash = "0x6bedf3685252745ac4f376f43c63c0594b2e146c7005d8eea206f2edc9f497f"
original_class_hash = "0x6bedf3685252745ac4f376f43c63c0594b2e146c7005d8eea206f2edc9f497f"
abi = "manifests/dev/abis/base/models/p_war_models_proposal_pixel_recovery_rate.json"
name = "p_war::models::proposal::pixel_recovery_rate"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "rate"
type = "u64"
key = false
