kind = "DojoModel"
class_hash = "0x655e61f5c6c56d8c108b305917bfd5662a27ded56327668b368db5d093fc8ac"
original_class_hash = "0x655e61f5c6c56d8c108b305917bfd5662a27ded56327668b368db5d093fc8ac"
abi = "manifests/dev/abis/base/models/p_war_models_proposal_pixel_recovery_rate.json"
name = "p_war::models::proposal::pixel_recovery_rate"

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "rate"
type = "u32"
key = false
