kind = "DojoModel"
class_hash = "0x521927f0cda6737b67dd4c58897375494daa5dc7854d25ad1f1fdf1cffdb55d"
original_class_hash = "0x521927f0cda6737b67dd4c58897375494daa5dc7854d25ad1f1fdf1cffdb55d"
abi = "manifests/dev/abis/base/models/p_war_models_game_game.json"
name = "p_war::models::game::game"

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "start"
type = "u64"
key = false

[[members]]
name = "end"
type = "u64"
key = false

[[members]]
name = "proposals"
type = "usize"
key = false
