kind = "DojoModel"
class_hash = "0x2990f2162e60836c0a1a9eb010e7824dbec48fe9533186a2f12ba2f4f2bc9b9"
original_class_hash = "0x2990f2162e60836c0a1a9eb010e7824dbec48fe9533186a2f12ba2f4f2bc9b9"
abi = "manifests/dev/abis/base/models/p_war_models_proposal_proposal.json"
name = "p_war::models::proposal::proposal"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "index"
type = "usize"
key = true

[[members]]
name = "author"
type = "ContractAddress"
key = false

[[members]]
name = "proposal_type"
type = "ProposalType"
key = false

[[members]]
name = "args"
type = "Args"
key = false

[[members]]
name = "start"
type = "u64"
key = false

[[members]]
name = "end"
type = "u64"
key = false

[[members]]
name = "yes_px"
type = "u32"
key = false

[[members]]
name = "no_px"
type = "u32"
key = false
