kind = "DojoModel"
class_hash = "0x1c0f1c7398ad721741911143732944a6ebf22d283820ff6d157c9306d2aa47a"
original_class_hash = "0x1c0f1c7398ad721741911143732944a6ebf22d283820ff6d157c9306d2aa47a"
abi = "manifests/dev/abis/base/models/p_war_models_allowed_app_allowed_app.json"
name = "p_war::models::allowed_app::allowed_app"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "contract"
type = "ContractAddress"
key = true

[[members]]
name = "is_allowed"
type = "bool"
key = false
