kind = "DojoModel"
class_hash = "0x7205d86654030ef9bafb6f3e9f59fd92bb93f7e2d89a0b9a2aaecad65480fd1"
original_class_hash = "0x7205d86654030ef9bafb6f3e9f59fd92bb93f7e2d89a0b9a2aaecad65480fd1"
abi = "manifests/dev/abis/base/models/p_war_models_allowed_color_allowed_color.json"
name = "p_war::models::allowed_color::allowed_color"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "color"
type = "u32"
key = true

[[members]]
name = "is_allowed"
type = "bool"
key = false
