kind = "DojoModel"
class_hash = "0x58af23d54aad773a73bd22bbcb7e6d29f0b49643e8931f48df837c931b8a218"
original_class_hash = "0x58af23d54aad773a73bd22bbcb7e6d29f0b49643e8931f48df837c931b8a218"
abi = "manifests/dev/abis/base/models/p_war_models_board_game_id.json"
name = "p_war::models::board::game_id"

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "value"
type = "usize"
key = false
