kind = "DojoModel"
class_hash = "0x73f4c14a1b7cfadff6bdad338ebacc61fa1c429a6610fd00480312ec6f37180"
original_class_hash = "0x73f4c14a1b7cfadff6bdad338ebacc61fa1c429a6610fd00480312ec6f37180"
abi = "manifests/dev/base/abis/models/pixelaw-Player-30a1b371.json"
tag = "pixelaw-Player"
qualified_path = "p_war::models::player::player"
manifest_name = "pixelaw-Player-30a1b371"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "max_px"
type = "u32"
key = false

[[members]]
name = "num_owns"
type = "u32"
key = false

[[members]]
name = "num_commit"
type = "u32"
key = false

[[members]]
name = "current_px"
type = "u32"
key = false

[[members]]
name = "last_date"
type = "u64"
key = false

[[members]]
name = "is_banned"
type = "bool"
key = false
