kind = "DojoModel"
class_hash = "0x7061fde93c6cf87511892ac88bc9d5443971aaf07983022821d3f0e5407b95"
original_class_hash = "0x7061fde93c6cf87511892ac88bc9d5443971aaf07983022821d3f0e5407b95"
abi = "manifests/dev/base/abis/models/pixelaw-GuildContractAddress-6a64b8e1.json"
tag = "pixelaw-GuildContractAddress"
qualified_path = "p_war::systems::actions::p_war_actions::guild_contract_address"
manifest_name = "pixelaw-GuildContractAddress-6a64b8e1"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false
