kind = "DojoModel"
class_hash = "0x2e21c14e524e53add7e001d5ff402bbb8573d8bfabfee7025eaa755aa6e729f"
original_class_hash = "0x2e21c14e524e53add7e001d5ff402bbb8573d8bfabfee7025eaa755aa6e729f"
abi = "manifests/dev/base/abis/models/pixelaw-AllowedApp-4aa27058.json"
tag = "pixelaw-AllowedApp"
qualified_path = "p_war::models::allowed_app::allowed_app"
manifest_name = "pixelaw-AllowedApp-4aa27058"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "contract"
type = "ContractAddress"
key = true

[[members]]
name = "is_allowed"
type = "bool"
key = false
