kind = "DojoModel"
class_hash = "0x4eb28e2e4c9f69487e5479cacac150e52666d072315dc8e3547b32f977976e0"
original_class_hash = "0x4eb28e2e4c9f69487e5479cacac150e52666d072315dc8e3547b32f977976e0"
abi = "manifests/dev/base/abis/models/pixelaw-Game-5c1fa23f.json"
tag = "pixelaw-Game"
qualified_path = "p_war::models::game::game"
manifest_name = "pixelaw-Game-5c1fa23f"

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "start"
type = "u64"
key = false

[[members]]
name = "end"
type = "u64"
key = false

[[members]]
name = "proposal_idx"
type = "usize"
key = false

[[members]]
name = "coeff_own_pixels"
type = "u32"
key = false

[[members]]
name = "coeff_commits"
type = "u32"
key = false

[[members]]
name = "winner_config"
type = "u32"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "guild_ids"
type = "Span<u32>"
key = false

[[members]]
name = "guild_count"
type = "usize"
key = false
