[world]
description = "PixeLAW world"
name = "pixelaw"
seed = "pixelaw"

[world.socials]
x = "https://x.com/0xpixelaw"
github = "https://github.com/pixelaw"

[namespace]
default = "pixelaw"
mappings = {}

[env]
rpc_url = "https://api.cartridge.gg/x/p-war-dev/katana/"
account_address = "0x1c6289fe4a0eeee86b5f6ef0f8d38056983b4a001cf1e0a812d6127c50866e4"
private_key = "0x6312f565a8634612a0c5a0032e2937645d06633ab3878bc15e67e07b6e3517c"
world_address = "0x263ae44e5414519a5c5a135cccaf3d9d7ee196d37e8de47a178da91f3de9b34"
