[world]
description = "P-WAR"
name = "p_war"
seed = "pixelaw"

[namespace]
default = "p_war"
mappings = {}

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x01d09b5e00f376337603943fc12715e439e91c0039f353b1cc48bb278dfa99d5"

[writers]
# GUILD
"p_war-Guild" = ["p_war-guild_actions"]
# P-WAR
"p_war-AllowedApp" = ["p_war-p_war_actions"]
"p_war-Board" = ["p_war-p_war_actions", "p_war-propose_actions"]
"p_war-AllowedColor" = ["p_war-p_war_actions", "p_war-propose_actions"]
"p_war-PaletteColors" = ["p_war-p_war_actions", "p_war-propose_actions"]
"p_war-PWarPixel" = ["p_war-p_war_actions"]
"p_war-Game" = ["p_war-p_war_actions"]
"p_war-GameId" = ["p_war-p_war_actions"]
"p_war-GamePalette" = ["p_war-p_war_actions", "p_war-propose_actions"]
"p_war-InPalette" = ["p_war-p_war_actions", "p_war-propose_actions"]
"p_war-Player" = ["p_war-p_war_actions", "p_war-propose_actions", "p_war-voting_actions"]
"p_war-PixelRecoveryRate" = ["p_war-p_war_actions"]
# PROPOSE
"p_war-Proposal" = ["p_war-propose_actions", "p_war-voting_actions"]
# VOTING
"p_war-PlayerVote" = ["p_war-voting_actions"]
