[world]
description = "PixeLAW world"
name = "pixelaw"
seed = "pixelaw"

[world.socials]
x = "https://x.com/0xpixelaw"
github = "https://github.com/pixelaw"

[namespace]
default = "pixelaw"
mappings = {}

[env]
rpc_url = "https://api.cartridge.gg/x/pwar-dev/katana/"
account_address = "0xc8bf87d6b8194c295e53a08d8df64d23bf987525d790ba8d5415c717378a06"
private_key = "0x3c9f3facdfc249265f5f096e8afa53adbdb371773be92ea4d1700d113861765"
world_address = "0x263ae44e5414519a5c5a135cccaf3d9d7ee196d37e8de47a178da91f3de9b34"
