[package]
cairo-version = "=2.8.4"
name = "p_war"
version = "0.3.54"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { git = "https://github.com/pixelaw/core", tag = "v0.5.10" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.1" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "pixelaw::core::models::pixel::Pixel",
    "pixelaw::core::models::pixel::PixelUpdate",
    "pixelaw::core::models::queue::QueueItem",
    "pixelaw::core::models::registry::App",
    "pixelaw::core::models::registry::AppName",
    "pixelaw::core::utils::get_core_actions",
    "pixelaw::core::models::registry::CoreActionsAddress",
    "pixelaw::core::actions::actions",
    "pixelaw::core::actions::IActionsDispatcher",
    "pixelaw::core::actions::IActionsDispatcherTrait"
]

[tool.fmt]
sort-module-level-items = true

[scripts]
init = "./scripts/init.sh"
