[package]
cairo-version = "=2.8.4"
name = "p_war"
version = "0.3.54"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { git = "https://github.com/pixelaw/core", tag = "v0.5.15" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.4" }
pixelaw_test_helpers = { git = "https://github.com/pixelaw/core", tag = "v0.5.15" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
    "dojo::world::world_contract::world",
    "pixelaw::core::actions::actions",
]

[tool.fmt]
sort-module-level-items = true

[profile.sepolia]

[scripts]
ready_for_deployment = "bash ./scripts/ready_for_deployment.sh"
initialize = "bash ./scripts/default_auth.sh"
upload_manifest = "bash ./scripts/upload_manifest.sh"
ready_for_deployment_zsh = "zsh ./scripts/ready_for_deployment.sh"
initialize_zsh = "zsh ./scripts/default_auth.sh"
upload_manifest_zsh = "zsh ./scripts/upload_manifest.sh"
