[package]
cairo-version = "=2.8.4"
name = "p_war"
version = "0.3.54"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { git = "https://github.com/pixelaw/core", tag = "v0.5.10" }
#pixelaw = { path = "../core/contracts" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.1" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.1" }
pixelaw_test_helpers = { git = "https://github.com/pixelaw/core", tag = "v0.5.10" }
#pixelaw_test_helpers = { path = "../core/test_helpers" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
    "dojo::world::world_contract::world",
    "pixelaw::core::actions::actions",
]

[tool.fmt]
sort-module-level-items = true

[scripts]
init = "./scripts/init.sh"
