kind = "DojoModel"
class_hash = "0x404d31fa774f450e44ff386730f3f43c2932d7cfcc55251e2a0ef2c77f5dc96"
original_class_hash = "0x404d31fa774f450e44ff386730f3f43c2932d7cfcc55251e2a0ef2c77f5dc96"
abi = "manifests/dev/base/abis/models/pixelaw-Proposal-49e1daf5.json"
tag = "pixelaw-Proposal"
qualified_path = "p_war::models::proposal::proposal"
manifest_name = "pixelaw-Proposal-49e1daf5"

[[members]]
name = "game_id"
type = "usize"
key = true

[[members]]
name = "index"
type = "usize"
key = true

[[members]]
name = "author"
type = "ContractAddress"
key = false

[[members]]
name = "proposal_type"
type = "u8"
key = false

[[members]]
name = "target_args_1"
type = "u32"
key = false

[[members]]
name = "target_args_2"
type = "u32"
key = false

[[members]]
name = "start"
type = "u64"
key = false

[[members]]
name = "end"
type = "u64"
key = false

[[members]]
name = "yes_px"
type = "u32"
key = false

[[members]]
name = "no_px"
type = "u32"
key = false

[[members]]
name = "is_activated"
type = "bool"
key = false
