[world]
kind = "WorldContract"
class_hash = "0x301ba8a1a13cec9291b049dea531f73a600e0812908cefa26d17214da411e9c"
original_class_hash = "0x301ba8a1a13cec9291b049dea531f73a600e0812908cefa26d17214da411e9c"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x60916a73fe631fcba3b2a930e21c6f7bb2533ea398c7bfa75c72f71a8709fc2"
seed = "p_war"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://127.0.0.1:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x2dc8bfc2e33f2e6966cbd9c2e0856d63250549c2a8258884cacb7ba35c427de"
class_hash = "0x777fd0c408dd44d17a85cc1553b3396c4645ce3ab6a11edb26bf1a0a68b1ced"
original_class_hash = "0x777fd0c408dd44d17a85cc1553b3396c4645ce3ab6a11edb26bf1a0a68b1ced"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/p_war_systems_actions_p_war_actions.json"
reads = []
writes = []
computed = []
name = "p_war::systems::actions::p_war_actions"

[[contracts]]
kind = "DojoContract"
address = "0x481aadb9eab76d625be9d0ab0af0155c9f162fd3af1113abd0d0308ddb9346e"
class_hash = "0x783cbadcce68d8d5269f62ff16562e5acbab9f9d8cd3d76d887c3929e119740"
original_class_hash = "0x783cbadcce68d8d5269f62ff16562e5acbab9f9d8cd3d76d887c3929e119740"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/p_war_systems_propose_propose.json"
reads = []
writes = []
computed = []
name = "p_war::systems::propose::propose"

[[contracts]]
kind = "DojoContract"
address = "0x405fdfa192f0a756c50dc081d0a4a10afbc5ed29a774665ab6a34cef4d4a549"
class_hash = "0x78696d9020dd83df7ac47df865b4517750f3d59bb9964bcac7f44b8ed97220"
original_class_hash = "0x78696d9020dd83df7ac47df865b4517750f3d59bb9964bcac7f44b8ed97220"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/p_war_systems_voting_voting.json"
reads = []
writes = []
computed = []
name = "p_war::systems::voting::voting"

[[contracts]]
kind = "DojoContract"
address = "0x665c9893b7694bf5329353f4c0beeed767819218f9f26e5576015248399bcf3"
class_hash = "0x192b0f77607ad6e522be8893e67f71eb8a27b56c5ab820043c283be5134291"
original_class_hash = "0x192b0f77607ad6e522be8893e67f71eb8a27b56c5ab820043c283be5134291"
base_class_hash = "0x0"
abi = "manifests/dev/abis/deployments/contracts/pixelaw_core_actions_actions.json"
reads = []
writes = []
computed = []
name = "pixelaw::core::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x1c0f1c7398ad721741911143732944a6ebf22d283820ff6d157c9306d2aa47a"
original_class_hash = "0x1c0f1c7398ad721741911143732944a6ebf22d283820ff6d157c9306d2aa47a"
abi = "manifests/dev/abis/deployments/models/p_war_models_allowed_app_allowed_app.json"
name = "p_war::models::allowed_app::allowed_app"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "contract"
type = "ContractAddress"
key = true

[[models.members]]
name = "is_allowed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7205d86654030ef9bafb6f3e9f59fd92bb93f7e2d89a0b9a2aaecad65480fd1"
original_class_hash = "0x7205d86654030ef9bafb6f3e9f59fd92bb93f7e2d89a0b9a2aaecad65480fd1"
abi = "manifests/dev/abis/deployments/models/p_war_models_allowed_color_allowed_color.json"
name = "p_war::models::allowed_color::allowed_color"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "color"
type = "u32"
key = true

[[models.members]]
name = "is_allowed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5dd036d17a36ae5166b87113c89bb1e37c59ca6edbfdc35f22102ab45cfadbe"
original_class_hash = "0x5dd036d17a36ae5166b87113c89bb1e37c59ca6edbfdc35f22102ab45cfadbe"
abi = "manifests/dev/abis/deployments/models/p_war_models_allowed_color_palette_colors.json"
name = "p_war::models::allowed_color::palette_colors"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "idx"
type = "u32"
key = true

[[models.members]]
name = "color"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2429cdd90cc9d51a903b0c8bbd3e19271f823937aab60f5b444200635b04044"
original_class_hash = "0x2429cdd90cc9d51a903b0c8bbd3e19271f823937aab60f5b444200635b04044"
abi = "manifests/dev/abis/deployments/models/p_war_models_board_board.json"
name = "p_war::models::board::board"

[[models.members]]
name = "id"
type = "usize"
key = true

[[models.members]]
name = "origin"
type = "Position"
key = false

[[models.members]]
name = "width"
type = "u32"
key = false

[[models.members]]
name = "height"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x58af23d54aad773a73bd22bbcb7e6d29f0b49643e8931f48df837c931b8a218"
original_class_hash = "0x58af23d54aad773a73bd22bbcb7e6d29f0b49643e8931f48df837c931b8a218"
abi = "manifests/dev/abis/deployments/models/p_war_models_board_game_id.json"
name = "p_war::models::board::game_id"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "usize"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3a759caf62afb2fd084ecc63d77ec528c50774246b658c9ac485915707676af"
original_class_hash = "0x3a759caf62afb2fd084ecc63d77ec528c50774246b658c9ac485915707676af"
abi = "manifests/dev/abis/deployments/models/p_war_models_board_p_war_pixel.json"
name = "p_war::models::board::p_war_pixel"

[[models.members]]
name = "position"
type = "Position"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xed13224574e2416c6c1b7064d344cd64cb422f2e3d8cddfb8582307b170d72"
original_class_hash = "0xed13224574e2416c6c1b7064d344cd64cb422f2e3d8cddfb8582307b170d72"
abi = "manifests/dev/abis/deployments/models/p_war_models_game_game.json"
name = "p_war::models::game::game"

[[models.members]]
name = "id"
type = "usize"
key = true

[[models.members]]
name = "start"
type = "u64"
key = false

[[models.members]]
name = "end"
type = "u64"
key = false

[[models.members]]
name = "proposal_idx"
type = "usize"
key = false

[[models.members]]
name = "next_color_idx_to_change"
type = "usize"
key = false

[[models.members]]
name = "base_cost"
type = "u32"
key = false

[[models.members]]
name = "const_val"
type = "u32"
key = false

[[models.members]]
name = "coeff_own_pixels"
type = "u32"
key = false

[[models.members]]
name = "coeff_commits"
type = "u32"
key = false

[[models.members]]
name = "winner_config"
type = "u32"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d7e89f1f0ad7eee6af444dc7d9e4443d17a73d3f0f6a569bf0d776eca36d47"
original_class_hash = "0x3d7e89f1f0ad7eee6af444dc7d9e4443d17a73d3f0f6a569bf0d776eca36d47"
abi = "manifests/dev/abis/deployments/models/p_war_models_player_player.json"
name = "p_war::models::player::player"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_px"
type = "u32"
key = false

[[models.members]]
name = "num_owns"
type = "u32"
key = false

[[models.members]]
name = "num_commit"
type = "u32"
key = false

[[models.members]]
name = "current_px"
type = "u32"
key = false

[[models.members]]
name = "last_date"
type = "u64"
key = false

[[models.members]]
name = "is_banned"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6bedf3685252745ac4f376f43c63c0594b2e146c7005d8eea206f2edc9f497f"
original_class_hash = "0x6bedf3685252745ac4f376f43c63c0594b2e146c7005d8eea206f2edc9f497f"
abi = "manifests/dev/abis/deployments/models/p_war_models_proposal_pixel_recovery_rate.json"
name = "p_war::models::proposal::pixel_recovery_rate"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "rate"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7cf83b952d7db2c69ad3ead0357513c6b519daffae9a4f9928fb0ad1752dba5"
original_class_hash = "0x7cf83b952d7db2c69ad3ead0357513c6b519daffae9a4f9928fb0ad1752dba5"
abi = "manifests/dev/abis/deployments/models/p_war_models_proposal_player_vote.json"
name = "p_war::models::proposal::player_vote"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "index"
type = "usize"
key = true

[[models.members]]
name = "is_in_favor"
type = "bool"
key = false

[[models.members]]
name = "px"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2990f2162e60836c0a1a9eb010e7824dbec48fe9533186a2f12ba2f4f2bc9b9"
original_class_hash = "0x2990f2162e60836c0a1a9eb010e7824dbec48fe9533186a2f12ba2f4f2bc9b9"
abi = "manifests/dev/abis/deployments/models/p_war_models_proposal_proposal.json"
name = "p_war::models::proposal::proposal"

[[models.members]]
name = "game_id"
type = "usize"
key = true

[[models.members]]
name = "index"
type = "usize"
key = true

[[models.members]]
name = "author"
type = "ContractAddress"
key = false

[[models.members]]
name = "proposal_type"
type = "ProposalType"
key = false

[[models.members]]
name = "args"
type = "Args"
key = false

[[models.members]]
name = "start"
type = "u64"
key = false

[[models.members]]
name = "end"
type = "u64"
key = false

[[models.members]]
name = "yes_px"
type = "u32"
key = false

[[models.members]]
name = "no_px"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6ad2fad00fbb98d63faa81e4a4d3289919296e643edd09244e359b19a9f0304"
original_class_hash = "0x6ad2fad00fbb98d63faa81e4a4d3289919296e643edd09244e359b19a9f0304"
abi = "manifests/dev/abis/deployments/models/pixelaw_apps_snake_app_snake.json"
name = "pixelaw::apps::snake::app::snake"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "length"
type = "u8"
key = false

[[models.members]]
name = "first_segment_id"
type = "u32"
key = false

[[models.members]]
name = "last_segment_id"
type = "u32"
key = false

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "is_dying"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xa5fff6fee52fd6a9d07e39f7039926783a2d8fc397a87617593c689124e113"
original_class_hash = "0xa5fff6fee52fd6a9d07e39f7039926783a2d8fc397a87617593c689124e113"
abi = "manifests/dev/abis/deployments/models/pixelaw_apps_snake_app_snake_segment.json"
name = "pixelaw::apps::snake::app::snake_segment"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "previous_id"
type = "u32"
key = false

[[models.members]]
name = "next_id"
type = "u32"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_color"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_text"
type = "felt252"
key = false

[[models.members]]
name = "pixel_original_app"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x55935fbd47fb70609ca521bbafaa69a03919f77c45bb8ad0e221af4658a9a6b"
original_class_hash = "0x55935fbd47fb70609ca521bbafaa69a03919f77c45bb8ad0e221af4658a9a6b"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_permissions_permissions.json"
name = "pixelaw::core::models::permissions::permissions"

[[models.members]]
name = "allowing_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "allowed_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "permission"
type = "Permission"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x19bf5119a6b23d3f098888ea27e5639d5b89ccf046d22e00c767cd4d3f78d9d"
original_class_hash = "0x19bf5119a6b23d3f098888ea27e5639d5b89ccf046d22e00c767cd4d3f78d9d"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_pixel_pixel.json"
name = "pixelaw::core::models::pixel::pixel"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "created_at"
type = "u64"
key = false

[[models.members]]
name = "updated_at"
type = "u64"
key = false

[[models.members]]
name = "app"
type = "ContractAddress"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4a448f9e37c98cc9af18ed6b5f0e144af59dc7ebb28fd553ee27e06d1e11d1c"
original_class_hash = "0x4a448f9e37c98cc9af18ed6b5f0e144af59dc7ebb28fd553ee27e06d1e11d1c"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_queue_queue_item.json"
name = "pixelaw::core::models::queue::queue_item"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "valid"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x74c630be9062098affb2ac8b27955ebaa8c863319800213a34ccc02ca97fc9"
original_class_hash = "0x74c630be9062098affb2ac8b27955ebaa8c863319800213a34ccc02ca97fc9"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_registry_app.json"
name = "pixelaw::core::models::registry::app"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "manifest"
type = "felt252"
key = false

[[models.members]]
name = "icon"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2fbf92676699542bb22322de6b8c9930c28a017b89f444ebdc7fb293496295d"
original_class_hash = "0x2fbf92676699542bb22322de6b8c9930c28a017b89f444ebdc7fb293496295d"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_registry_app_name.json"
name = "pixelaw::core::models::registry::app_name"

[[models.members]]
name = "name"
type = "felt252"
key = true

[[models.members]]
name = "system"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x21694db3f07ef20ac056336fd80757d8883bae2a2329ca9ade1d681fe9ae883"
original_class_hash = "0x21694db3f07ef20ac056336fd80757d8883bae2a2329ca9ade1d681fe9ae883"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_registry_app_user.json"
name = "pixelaw::core::models::registry::app_user"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x29faa42389b762ddb248311c81d68095c0fec2cfd7810b31e62af19675b0afb"
original_class_hash = "0x29faa42389b762ddb248311c81d68095c0fec2cfd7810b31e62af19675b0afb"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_registry_core_actions_address.json"
name = "pixelaw::core::models::registry::core_actions_address"

[[models.members]]
name = "key"
type = "felt252"
key = true

[[models.members]]
name = "value"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x40bff7008f593e3fa201c4b22e5cf172217620a5605bdab71e09d9a9a9d781a"
original_class_hash = "0x40bff7008f593e3fa201c4b22e5cf172217620a5605bdab71e09d9a9a9d781a"
abi = "manifests/dev/abis/deployments/models/pixelaw_core_models_registry_instruction.json"
name = "pixelaw::core::models::registry::instruction"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "selector"
type = "felt252"
key = true

[[models.members]]
name = "instruction"
type = "felt252"
key = false
