kind = "DojoContract"
class_hash = "0x12f14528aa1dfc642ac4bfc19e418102cba2e004995a34cab737bd50c1e532b"
original_class_hash = "0x12f14528aa1dfc642ac4bfc19e418102cba2e004995a34cab737bd50c1e532b"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/p_war_systems_propose_propose.json"
reads = []
writes = []
computed = []
name = "p_war::systems::propose::propose"
