kind = "DojoContract"
class_hash = "0x6f6ccb38ccf4fa5456f18b40b2c3f133730e62a0680746dc5afe6f3a03ce03b"
original_class_hash = "0x6f6ccb38ccf4fa5456f18b40b2c3f133730e62a0680746dc5afe6f3a03ce03b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-guild_actions-4c9f5931.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-guild_actions"
systems = [
    "add_member",
    "join_guild",
    "remove_member",
]
manifest_name = "pixelaw-guild_actions-4c9f5931"
