kind = "DojoContract"
class_hash = "0x1a367552a5c071c3632eb91e7bdb42d6abe1b92ad1ae1710a036b487f695288"
original_class_hash = "0x1a367552a5c071c3632eb91e7bdb42d6abe1b92ad1ae1710a036b487f695288"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-p_war_actions-60819afd.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_war_actions"
systems = [
    "on_pre_update",
    "on_post_update",
    "set_pixel",
    "init",
    "interact",
    "create_game_guilds",
    "place_pixel",
    "update_pixel",
    "end_game",
]
manifest_name = "pixelaw-p_war_actions-60819afd"
