kind = "DojoContract"
class_hash = "0x7cc823538eb9a92fcd8af9cdb8d4293fe2c8b1cc090623670721f32b490c0ff"
original_class_hash = "0x7cc823538eb9a92fcd8af9cdb8d4293fe2c8b1cc090623670721f32b490c0ff"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-propose_actions-4ee7028a.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-propose_actions"
systems = ["activate_proposal"]
manifest_name = "pixelaw-propose_actions-4ee7028a"
