kind = "DojoContract"
class_hash = "0x27cb0ed43970c5111226c6909cea79d7980ccaa4f001cd8eff6fc9f03db1660"
original_class_hash = "0x27cb0ed43970c5111226c6909cea79d7980ccaa4f001cd8eff6fc9f03db1660"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-p_war_actions-60819afd.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_war_actions"
systems = [
    "on_pre_update",
    "on_post_update",
    "set_pixel",
    "init",
    "interact",
    "place_pixel",
    "update_pixel",
    "end_game",
]
manifest_name = "pixelaw-p_war_actions-60819afd"
