kind = "DojoContract"
class_hash = "0x806fe6e6de3d9ea410944be8e0bb9a6ea6aa22761a7e78dcf6080ecba54e"
original_class_hash = "0x806fe6e6de3d9ea410944be8e0bb9a6ea6aa22761a7e78dcf6080ecba54e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-p_war_actions-60819afd.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_war_actions"
systems = [
    "on_pre_update",
    "on_post_update",
    "set_pixel",
    "init",
    "interact",
    "place_pixel",
    "update_pixel",
    "end_game",
]
manifest_name = "pixelaw-p_war_actions-60819afd"
