kind = "DojoContract"
class_hash = "0x16dce3a4c8116fa7d866bd8896050201427a10214befa642a93135b327bd250"
original_class_hash = "0x16dce3a4c8116fa7d866bd8896050201427a10214befa642a93135b327bd250"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-guild_actions-4c9f5931.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-guild_actions"
systems = [
    "add_member",
    "join_guild",
    "remove_member",
]
manifest_name = "pixelaw-guild_actions-4c9f5931"
