kind = "DojoContract"
class_hash = "0x66f3cdbcc21647323dcad1d5857d6822912f0d44857c7dc90cf7d67314ad288"
original_class_hash = "0x66f3cdbcc21647323dcad1d5857d6822912f0d44857c7dc90cf7d67314ad288"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-propose_actions-4ee7028a.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-propose_actions"
systems = ["activate_proposal"]
manifest_name = "pixelaw-propose_actions-4ee7028a"
